//! The AAC decoder: `raw_data_block` / `er_raw_data_block` → channel elements →
//! spectral tools → synthesis → PCM (ISO 14496-3 §4.4 / §4.6).
//!
//! Coverage: AAC Main (backward-adaptive prediction), LC, SSR (gain control
//! parsed and ignored, as every practical decoder does), LTP; the 960-sample
//! frame variant; ER AAC-LC/LTP, ER AAC-LD (512/480) and ER AAC-ELD (low-delay
//! filterbank); every channel configuration 1-7 and 11-14 plus PCE-described
//! programs; coupling channel elements (dependent before/after TNS and
//! independent after IMDCT); PNS, intensity and M/S stereo, pulses, TNS.
//! HE-AAC (SBR/PS) is layered on top in [`crate::sbr`].
//!
//! Output order and element routing follow FFmpeg's model (see [`layout`]) so a
//! multichannel stream comes out in the same channel order, and noise bands are
//! generated by the same LCG, which is what lets the conformance census compare
//! sample-for-sample.

pub(crate) mod channel;
pub mod layout;
mod synth;
pub(crate) mod tools;

pub(crate) use channel::TNS_MAX_LONG;

use crate::bits::BitReader;
use crate::config::{aot, StreamConfig};
use crate::ics::WindowSequence;
use crate::tables::SCALEFACTOR_BOOK;
use crate::{DecodedAudio, Error, Result};
use channel::{decode_ics, decode_ltp, parse_ics_info, ChannelData, Ics, Syntax, MAX_PREDICTORS};
use layout::{OutputConfig, Tag, TYPE_CCE, TYPE_CPE, TYPE_LFE, TYPE_SCE};
use tools::{Coupling, PredState};

const ID_SCE: u32 = 0;
const ID_CPE: u32 = 1;
const ID_CCE: u32 = 2;
const ID_LFE: u32 = 3;
const ID_DSE: u32 = 4;
const ID_PCE: u32 = 5;
const ID_FIL: u32 = 6;
const ID_END: u32 = 7;

const EXT_DYNAMIC_RANGE: u32 = 11;
const EXT_SBR_DATA: u32 = 13;
const EXT_SBR_DATA_CRC: u32 = 14;

/// One channel's persistent decode state + this frame's payload.
#[derive(Clone)]
pub(crate) struct Sce {
    pub ics: Ics,
    pub data: ChannelData,
    pub saved: Vec<f32>,
    pub output: Vec<f32>,
    pub ltp_state: Vec<f32>,
    pub pred: Vec<PredState>,
    pub pred_init: bool,
}

impl Sce {
    fn new() -> Sce {
        Sce {
            ics: Ics::default(),
            data: ChannelData::default(),
            saved: vec![0.0; 1536],
            output: vec![0.0; 2048],
            ltp_state: vec![0.0; 3072],
            pred: vec![PredState::default(); MAX_PREDICTORS],
            pred_init: false,
        }
    }
}

/// A channel element (SCE/LFE use `ch[0]`; CPE both; CCE `ch[0]` + coupling).
#[derive(Clone)]
pub(crate) struct Element {
    pub ch: [Sce; 2],
    pub coup: Coupling,
    pub present: bool,
    pub ms_mask: Vec<bool>,
    pub ms_present: u8,
    pub common_window: bool,
    /// Raw SBR extension payloads seen this frame (consumed by the SBR stage).
    pub sbr_payload: Option<(Vec<u8>, usize, bool)>,
    pub sbr: Option<Box<crate::sbr::dec::SbrChannelState>>,
}

impl Element {
    fn new() -> Element {
        Element {
            ch: [Sce::new(), Sce::new()],
            coup: Coupling::default(),
            present: false,
            ms_mask: vec![false; 128],
            ms_present: 0,
            common_window: false,
            sbr_payload: None,
            sbr: None,
        }
    }
}

/// Stateful AAC decoder for one elementary stream.
pub struct Decoder {
    cfg: StreamConfig,
    syntax: Syntax,
    windows: synth::Windows,
    ld_sine: Vec<f32>,
    ld_low_overlap: Vec<f32>,
    elements: Vec<Vec<Option<Box<Element>>>>,
    oc: OutputConfig,
    /// The configuration's `channelConfiguration` (0 = PCE-routed).
    chan_config: u8,
    tags_mapped: usize,
    rng: u32,
    saw_sbr: bool,
    /// SBR: Some(true) explicitly present, Some(false) explicitly absent, None = unknown.
    sbr_state: Option<bool>,
    ps_state: Option<bool>,
    locked: bool,
    buf: Vec<f32>,
    pub(crate) sbr_ctx: Option<Box<crate::sbr::dec::SbrDecoderCtx>>,
    /// No layout known (raw access units with no config, or an ADTS
    /// `channel_configuration` of 0 without a PCE): the first frame's elements
    /// define it, in arrival order.
    discovery: Option<Vec<Tag>>,
}

impl Decoder {
    /// A plain AAC-LC decoder at `sample_rate` (layout learned from the stream).
    pub fn new(sample_rate: u32) -> Decoder {
        Decoder::with_stream_config(StreamConfig::lc(2, sample_rate, 0))
            .unwrap_or_else(|_| Decoder::with_stream_config(StreamConfig::lc(2, 44100, 0)).unwrap())
    }

    /// A decoder for a fully parsed configuration.
    pub fn with_stream_config(cfg: StreamConfig) -> Result<Decoder> {
        let syntax = Syntax {
            aot: cfg.object_type,
            sf_index: cfg.sf_index,
            frame_len: cfg.frame_length,
        };
        match cfg.object_type {
            aot::AAC_MAIN | aot::AAC_LC | aot::AAC_SSR | aot::AAC_LTP | aot::ER_AAC_LC | aot::ER_AAC_LTP => {}
            aot::ER_AAC_LD => {
                if !(3..=7).contains(&cfg.sf_index) {
                    return Err(Error::invalid("aac: invalid low-delay sampling rate"));
                }
            }
            aot::ER_AAC_ELD => {}
            o => {
                return Err(Error::unsupported(format!("aac: object type {o} not supported")));
            }
        }
        if cfg.section_data_resilience || cfg.scalefactor_data_resilience || cfg.spectral_data_resilience {
            return Err(Error::unsupported(
                "aac: error-resilience data tools (HCR/RVLC/VCB11) are not supported",
            ));
        }
        let fl = match cfg.object_type {
            aot::ER_AAC_LD | aot::ER_AAC_ELD => cfg.frame_length,
            _ => cfg.frame_length,
        };
        let win_len = if fl <= 512 { 1024 } else { fl };
        let mut d = Decoder {
            windows: synth::Windows::new(win_len),
            ld_sine: crate::dsp::sine_window(2 * fl)[..fl].to_vec(),
            ld_low_overlap: crate::dsp::sine_window(2 * (fl / 4))[..fl / 4].to_vec(),
            syntax,
            elements: (0..4).map(|_| (0..16).map(|_| None).collect()).collect(),
            oc: OutputConfig::default(),
            chan_config: cfg.channel_config,
            tags_mapped: 0,
            rng: 0x1f2e3d4c,
            saw_sbr: false,
            sbr_state: if cfg.sbr {
                Some(true)
            } else if cfg.sbr_explicitly_absent {
                Some(false)
            } else {
                None
            },
            ps_state: if cfg.ps { Some(true) } else { None },
            locked: false,
            buf: vec![0.0; 2048],
            sbr_ctx: None,
            discovery: if cfg.channel_config == 0 && cfg.pce.is_none() { Some(Vec::new()) } else { None },
            cfg,
        };
        d.configure_initial()?;
        Ok(d)
    }

    /// The configuration this decoder runs.
    pub fn stream_config(&self) -> &StreamConfig {
        &self.cfg
    }

    fn configure_initial(&mut self) -> Result<()> {
        let map = if let Some(p) = &self.cfg.pce {
            layout::pce_layout(p)
        } else if self.cfg.channel_config != 0 {
            layout::default_layout(self.cfg.channel_config, false)
                .ok_or_else(|| Error::unsupported("aac: unsupported channel configuration"))?
        } else {
            return Ok(()); // layout learned from an in-band PCE
        };
        // A mono program carrying SBR may carry implicit PS: FFmpeg outputs it
        // as stereo, and so do we.
        let mono = map.iter().map(|t| 1 + (t.syn_ele == TYPE_CPE) as usize * (t.pos != 5) as usize).sum::<usize>() <= 1;
        if !mono {
            self.ps_state = Some(false);
        } else if self.sbr_state == Some(true) && self.ps_state.is_none() {
            self.ps_state = Some(true);
        }
        self.output_configure(map);
        Ok(())
    }

    /// Positions for elements discovered in arrival order: a sequence matching a
    /// standard configuration takes that configuration's positions.
    fn discovered_layout(rows: Vec<Tag>) -> Vec<Tag> {
        for cc in [1u8, 2, 3, 4, 5, 6, 7] {
            if let Some(std_rows) = layout::default_layout(cc, false) {
                if std_rows.len() == rows.len() && std_rows.iter().zip(&rows).all(|(a, b)| a.syn_ele == b.syn_ele) {
                    return std_rows
                        .iter()
                        .zip(&rows)
                        .map(|(a, b)| Tag { syn_ele: b.syn_ele, id: b.id, pos: a.pos })
                        .collect();
                }
            }
        }
        rows.into_iter()
            .map(|r| Tag { pos: if r.syn_ele == TYPE_LFE { layout::POS_LFE } else if r.syn_ele == TYPE_CCE { layout::POS_CC } else { layout::POS_FRONT }, ..r })
            .collect()
    }

    pub(crate) fn ps_on(&self) -> bool {
        self.ps_state == Some(true)
    }

    fn output_configure(&mut self, map: Vec<Tag>) {
        self.oc = OutputConfig::configure(map, self.ps_on());
        self.discovery = None;
        for ty in 0..4 {
            for iid in 0..16 {
                if self.oc.allocated[ty][iid] && self.elements[ty][iid].is_none() {
                    self.elements[ty][iid] = Some(Box::new(Element::new()));
                }
            }
        }
    }

    /// Whether an SBR fill payload has been seen (implicit HE-AAC signalling).
    pub fn saw_sbr(&self) -> bool {
        self.saw_sbr
    }

    /// The output channel count of the current configuration.
    pub fn channels(&self) -> usize {
        self.oc.channels()
    }

    fn instance(&self, ty: u8, iid: u8) -> Option<(usize, usize)> {
        let (t, i) = (ty as usize, iid as usize);
        if self.elements[t][i].is_some() {
            Some((t, i))
        } else {
            None
        }
    }

    /// `ff_aac_get_che`: route an element (type, tag) to its instance.
    fn get_che(&mut self, ty: u8, tag: u8) -> Option<(usize, usize)> {
        if let Some(rows) = self.discovery.as_mut() {
            let t = ty as usize;
            if self.oc.tag_to_instance[t][tag as usize].is_none() {
                let iid = rows.iter().filter(|r| r.syn_ele == ty).count() as u8;
                rows.push(Tag { syn_ele: ty, id: tag, pos: layout::POS_FRONT });
                self.oc.tag_to_instance[t][tag as usize] = Some(iid);
                if self.elements[t][iid as usize].is_none() {
                    self.elements[t][iid as usize] = Some(Box::new(Element::new()));
                }
            }
            let iid = self.oc.tag_to_instance[t][tag as usize]?;
            return self.instance(ty, iid);
        }
        if self.chan_config == 0 {
            let iid = self.oc.tag_to_instance[ty as usize][tag as usize]?;
            return self.instance(ty, iid);
        }
        if self.tags_mapped == 0 && ty == TYPE_CPE && self.chan_config == 1 {
            // Mono configuration carrying a CPE: decode as stereo.
            self.output_configure(layout::default_layout(2, false).unwrap());
            self.chan_config = 2;
            self.ps_state = Some(false);
        }
        if self.tags_mapped == 0 && ty == TYPE_SCE && self.chan_config == 2 {
            // Stereo configuration carrying SCEs: two front SCEs.
            self.output_configure(vec![
                Tag { syn_ele: TYPE_SCE, id: 0, pos: layout::POS_FRONT },
                Tag { syn_ele: TYPE_SCE, id: 1, pos: layout::POS_FRONT },
            ]);
            if self.sbr_state == Some(true) {
                self.ps_state = None;
            }
        }
        let cc = self.chan_config;
        let tm = self.tags_mapped;
        let tags_per = |c: u8| -> usize {
            [0, 1, 1, 2, 3, 3, 4, 5, 0, 0, 0, 5, 5, 16, 5, 0][c as usize & 15]
        };
        let hit = |s: &mut Self, t: usize, i: usize| -> Option<(usize, usize)> {
            s.tags_mapped += 1;
            s.instance(t as u8, i as u8)
        };
        // The fall-through cascade of the reference's switch on chan_config.
        let level = match cc {
            14 => 0,
            13 => 1,
            12 | 7 => 2,
            11 => 3,
            6 => 4,
            5 => 5,
            4 => 6,
            3 | 2 => 7,
            1 => 8,
            _ => 9,
        };
        if level <= 0 && tm > 2 && ((ty == TYPE_CPE && tag < 3) || (ty == TYPE_LFE && tag < 1)) {
            return hit(self, ty as usize, tag as usize);
        }
        if level <= 1 && tm > 3 && ((ty == TYPE_CPE && tag < 8) || (ty == TYPE_SCE && tag < 6) || (ty == TYPE_LFE && tag < 2)) {
            return hit(self, ty as usize, tag as usize);
        }
        if level <= 2 && tm == 3 && ty == TYPE_CPE {
            return hit(self, TYPE_CPE as usize, 2);
        }
        if level <= 3 && tm == 3 && ty == TYPE_SCE {
            return hit(self, TYPE_SCE as usize, 1);
        }
        if level <= 4 && tm + 1 == tags_per(cc) && (ty == TYPE_LFE || ty == TYPE_SCE) {
            return hit(self, TYPE_LFE as usize, 0);
        }
        if level <= 5 && tm == 2 && ty == TYPE_CPE {
            return hit(self, TYPE_CPE as usize, 1);
        }
        if level <= 6 {
            if tm + 1 == tags_per(cc) && (ty == TYPE_LFE || ty == TYPE_SCE) {
                return hit(self, TYPE_SCE as usize, 1);
            }
            if tm == 2 && cc == 4 && ty == TYPE_SCE {
                return hit(self, TYPE_SCE as usize, 1);
            }
        }
        if level <= 7 {
            if tm == (cc != 2) as usize && ty == TYPE_CPE {
                return hit(self, TYPE_CPE as usize, 0);
            } else if tm == 1 && cc == 2 && ty == TYPE_SCE {
                return hit(self, TYPE_SCE as usize, 1);
            }
        }
        if level <= 8 && tm == 0 && ty == TYPE_SCE {
            return hit(self, TYPE_SCE as usize, 0);
        }
        None
    }

    fn el(&mut self, at: (usize, usize)) -> &mut Element {
        self.elements[at.0][at.1].as_mut().unwrap()
    }

    /// Decode one access unit (`raw_data_block` or `er_raw_data_block`).
    pub fn decode(&mut self, au: &[u8], pts: Option<i64>) -> Result<DecodedAudio> {
        Ok(self.decode_block(au, pts)?.0)
    }

    /// Decode one block and report how many bytes it occupied (byte-aligned
    /// after its `ID_END`), for containers that pack several per frame.
    pub fn decode_block(&mut self, au: &[u8], pts: Option<i64>) -> Result<(DecodedAudio, usize)> {
        let mut r = BitReader::new(au);
        if self.cfg.is_er() {
            self.decode_er_frame(&mut r)?;
        } else {
            self.decode_ga_frame(&mut r)?;
        }
        Ok((self.collect_output(pts), r.position().div_ceil(8)))
    }

    fn decode_ga_frame(&mut self, r: &mut BitReader) -> Result<()> {
        self.tags_mapped = 0;
        let mut presence = [[0u8; 16]; 4];
        let mut prev: Option<((usize, usize), u8)> = None;
        let mut audio_found = false;
        let mut pce_found = false;
        let payload_alignment = r.position();
        let sx = self.syntax;
        loop {
            let elem_type = r.read_bits(3)?;
            if elem_type == ID_END {
                break;
            }
            let mut elem_id = r.read_bits(4)? as usize;
            if self.oc.channels() == 0 && elem_type != ID_PCE && self.discovery.is_none() {
                return Err(Error::invalid("aac: channel element before any layout"));
            }
            let mut at = None;
            if elem_type < ID_DSE {
                let p = &mut presence[elem_type as usize][elem_id];
                if *p > 1 {
                    return Err(Error::invalid("aac: duplicate channel element"));
                }
                *p += 1;
                at = Some(
                    self.get_che(elem_type as u8, elem_id as u8)
                        .ok_or_else(|| Error::invalid("aac: channel element is not allocated"))?,
                );
                self.el(at.unwrap()).present = true;
            }
            match elem_type {
                ID_SCE | ID_LFE => {
                    let at = at.unwrap();
                    let rng = &mut self.rng;
                    let el = self.elements[at.0][at.1].as_mut().unwrap();
                    let sce = &mut el.ch[0];
                    decode_ics(r, &sx, &mut sce.ics, &mut sce.data, false, rng)?;
                    if sx.aot == aot::AAC_MAIN {
                        let (ics, data, pred, init) = (&sce.ics, &mut sce.data, &mut sce.pred, &mut sce.pred_init);
                        tools::apply_prediction(ics, sx.sf_index, &mut data.coeffs, pred, init);
                    }
                    audio_found = true;
                }
                ID_CPE => {
                    self.decode_cpe(r, at.unwrap())?;
                    audio_found = true;
                }
                ID_CCE => self.decode_cce(r, at.unwrap())?,
                ID_DSE => {
                    let align = r.read_bool()?;
                    let mut count = r.read_bits(8)? as usize;
                    if count == 255 {
                        count += r.read_bits(8)? as usize;
                    }
                    if align {
                        r.byte_align();
                    }
                    r.skip(8 * count)?;
                }
                ID_PCE => {
                    let p = crate::config::Pce::parse_after_tag(r, elem_id as u8, payload_alignment)?;
                    if !pce_found {
                        self.output_configure(layout::pce_layout(&p));
                        self.chan_config = 0;
                        pce_found = true;
                    }
                }
                ID_FIL => {
                    if elem_id == 15 {
                        elem_id += r.read_bits(8)? as usize - 1;
                    }
                    if r.bits_left() < 8 * elem_id {
                        return Err(Error::invalid("aac: fill element overruns the frame"));
                    }
                    let mut cnt = elem_id;
                    while cnt > 0 {
                        let used = self.decode_extension_payload(r, cnt, prev)?;
                        cnt = cnt.saturating_sub(used.max(1));
                    }
                }
                _ => unreachable!(),
            }
            if elem_type < ID_DSE {
                prev = Some((at.unwrap(), elem_type as u8));
            }
            if r.bits_left() < 3 {
                return Err(Error::invalid("aac: frame ends before ID_END"));
            }
        }
        if let Some(rows) = self.discovery.take() {
            if rows.is_empty() {
                self.discovery = Some(rows);
            } else {
                self.output_configure(Self::discovered_layout(rows));
            }
        }
        if self.oc.channels() == 0 {
            return Err(Error::Again);
        }
        self.spectral_to_sample();
        if audio_found {
            self.locked = true;
        }
        Ok(())
    }

    fn decode_er_frame(&mut self, r: &mut BitReader) -> Result<()> {
        self.tags_mapped = 0;
        let cc = self.chan_config;
        let rows = layout::default_layout(cc, false)
            .ok_or_else(|| Error::unsupported("aac: unknown ER channel configuration"))?;
        let sx = self.syntax;
        for row in rows {
            let at = self
                .get_che(row.syn_ele, row.id)
                .ok_or_else(|| Error::invalid("aac: channel element is not allocated"))?;
            self.el(at).present = true;
            if !sx.eld() {
                r.skip(4)?;
            }
            match row.syn_ele {
                TYPE_CPE => self.decode_cpe(r, at)?,
                _ => {
                    let rng = &mut self.rng;
                    let el = self.elements[at.0][at.1].as_mut().unwrap();
                    let sce = &mut el.ch[0];
                    decode_ics(r, &sx, &mut sce.ics, &mut sce.data, false, rng)?;
                }
            }
        }
        if sx.eld() && self.sbr_state == Some(true) {
            self.decode_eld_sbr(r)?;
        }
        self.spectral_to_sample();
        self.locked = true;
        Ok(())
    }

    fn decode_cpe(&mut self, r: &mut BitReader, at: (usize, usize)) -> Result<()> {
        let sx = self.syntax;
        let rng = &mut self.rng;
        let el = self.elements[at.0][at.1].as_mut().unwrap();
        let common_window = sx.eld() || r.read_bool()?;
        el.common_window = common_window;
        el.ms_present = 0;
        if common_window {
            parse_ics_info(r, &sx, &mut el.ch[0].ics)?;
            let kbd1 = el.ch[1].ics.info.window_shape_kbd;
            el.ch[1].ics = el.ch[0].ics.clone();
            el.ch[1].ics.prev_kbd = kbd1;
            if el.ch[1].ics.predictor_present && sx.aot != aot::AAC_MAIN {
                el.ch[1].ics.ltp.present = r.read_bool()?;
                if el.ch[1].ics.ltp.present {
                    let m = el.ch[1].ics.info.max_sfb as usize;
                    decode_ltp(r, &mut el.ch[1].ics.ltp, m)?;
                }
            }
            let msp = r.read_bits(2)? as u8;
            if msp == 3 {
                return Err(Error::invalid("aac: ms_mask_present = 3 is reserved"));
            }
            el.ms_present = msp;
            let info = &el.ch[0].ics.info;
            let n = info.num_window_groups * info.max_sfb as usize;
            for i in 0..n {
                el.ms_mask[i] = match msp {
                    1 => r.read_bool()?,
                    2 => true,
                    _ => false,
                };
            }
        }
        {
            let [c0, c1] = &mut el.ch;
            decode_ics(r, &sx, &mut c0.ics, &mut c0.data, common_window, rng)?;
            decode_ics(r, &sx, &mut c1.ics, &mut c1.data, common_window, rng)?;
        }
        if common_window {
            if el.ms_present != 0 {
                let [c0, c1] = &mut el.ch;
                tools::apply_ms(&c0.ics, &el.ms_mask, &mut c0.data, &mut c1.data);
            }
            if sx.aot == aot::AAC_MAIN {
                for c in el.ch.iter_mut() {
                    let (ics, data, pred, init) = (&c.ics, &mut c.data, &mut c.pred, &mut c.pred_init);
                    tools::apply_prediction(ics, sx.sf_index, &mut data.coeffs, pred, init);
                }
            }
        } else if sx.aot == aot::AAC_MAIN {
            for c in el.ch.iter_mut() {
                let (ics, data, pred, init) = (&c.ics, &mut c.data, &mut c.pred, &mut c.pred_init);
                tools::apply_prediction(ics, sx.sf_index, &mut data.coeffs, pred, init);
            }
        }
        let [c0, c1] = &mut el.ch;
        tools::apply_is(&c1.ics, el.ms_present != 0, &el.ms_mask, &c0.data, &mut c1.data);
        Ok(())
    }

    fn decode_cce(&mut self, r: &mut BitReader, at: (usize, usize)) -> Result<()> {
        let sx = self.syntax;
        let rng = &mut self.rng;
        let el = self.elements[at.0][at.1].as_mut().unwrap();
        let mut point = 2 * r.read_bit()? as u8;
        let num_coupled = r.read_bits(3)? as usize;
        let mut num_gain = 0usize;
        let mut targets = Vec::new();
        for _ in 0..=num_coupled {
            num_gain += 1;
            let is_cpe = r.read_bool()?;
            let id = r.read_bits(4)? as u8;
            let ch_select = if is_cpe {
                let s = r.read_bits(2)? as u8;
                if s == 3 {
                    num_gain += 1;
                }
                s
            } else {
                2
            };
            targets.push((if is_cpe { TYPE_CPE } else { TYPE_SCE }, id, ch_select));
        }
        point += (r.read_bool()? || (point >> 1) != 0) as u8;
        let sign = r.read_bool()?;
        let scale = [1.090_507_7f32, 1.189_207_1, std::f32::consts::SQRT_2, 2.0][r.read_bits(2)? as usize];
        decode_ics(r, &sx, &mut el.ch[0].ics, &mut el.ch[0].data, false, rng)?;
        let info = el.ch[0].ics.info.clone();
        let max_sfb = info.max_sfb as usize;
        let mut gains = vec![vec![0f32; 128]; num_gain];
        for (c, gc) in gains.iter_mut().enumerate() {
            let mut cge = true;
            let mut gain = 0i32;
            let mut gain_cache = 1.0f32;
            if c > 0 {
                cge = if point == tools::AFTER_IMDCT { true } else { r.read_bool()? };
                gain = if cge { SCALEFACTOR_BOOK.decode(r)? as i32 - 60 } else { 0 };
                gain_cache = scale.powf(-(gain as f32));
            }
            if point == tools::AFTER_IMDCT {
                gc[0] = gain_cache;
            } else {
                for g in 0..info.num_window_groups {
                    for sfb in 0..max_sfb {
                        let idx = g * max_sfb + sfb;
                        if el.ch[0].data.band_type[idx] != 0 {
                            if !cge {
                                let mut t = SCALEFACTOR_BOOK.decode(r)? as i32 - 60;
                                if t != 0 {
                                    let mut s = 1.0f32;
                                    gain += t;
                                    t = gain;
                                    if sign {
                                        s -= 2.0 * (t & 1) as f32;
                                        t >>= 1;
                                    }
                                    gain_cache = scale.powf(-(t as f32)) * s;
                                }
                            }
                            gc[idx] = gain_cache;
                        }
                    }
                }
            }
        }
        el.coup = Coupling {
            point,
            num_coupled,
            targets,
            gains,
        };
        Ok(())
    }

    /// `extension_payload` inside a fill element. Returns bytes consumed.
    fn decode_extension_payload(&mut self, r: &mut BitReader, cnt: usize, prev: Option<((usize, usize), u8)>) -> Result<usize> {
        let start = r.position();
        let ext = r.read_bits(4)?;
        match ext {
            EXT_SBR_DATA | EXT_SBR_DATA_CRC => {
                self.saw_sbr = true;
                let Some((at, prev_type)) = prev else {
                    r.skip(8 * cnt - 4)?;
                    return Ok(cnt);
                };
                if self.sbr_state == Some(false) {
                    r.skip(8 * cnt - 4)?;
                    return Ok(cnt);
                }
                if self.sbr_state.is_none() {
                    if self.locked {
                        // Implicit SBR first seen after the first frame: ignored.
                        r.skip(8 * cnt - 4)?;
                        return Ok(cnt);
                    }
                    self.sbr_state = Some(true);
                    if self.ps_state.is_none() && self.oc.channels() == 1 {
                        self.ps_state = Some(true);
                        let map = self.oc.map.clone();
                        self.output_configure(map);
                    }
                }
                // Hand the raw payload to the SBR stage.
                let bits = 8 * cnt - 4;
                let mut payload = Vec::with_capacity(cnt);
                let mut left = bits;
                while left >= 8 {
                    payload.push(r.read_bits(8)? as u8);
                    left -= 8;
                }
                if left > 0 {
                    payload.push((r.read_bits(left as u32)? << (8 - left)) as u8);
                }
                let el = self.el(at);
                el.sbr_payload = Some((payload, bits, ext == EXT_SBR_DATA_CRC));
                let _ = prev_type;
                Ok(cnt)
            }
            EXT_DYNAMIC_RANGE => {
                // Parsed for its length; DRC is metadata and not applied (as
                // in the reference decoder's default configuration).
                let mut n = 1usize;
                if r.read_bool()? {
                    r.skip(8)?;
                    n += 1;
                }
                if r.read_bool()? {
                    let mut k = 0;
                    loop {
                        r.skip(7)?;
                        k += 7;
                        if k >= 64 - 7 || !r.read_bool()? {
                            break;
                        }
                    }
                    n += k / 7;
                }
                let mut bands = 1usize;
                if r.read_bool()? {
                    let incr = r.read_bits(4)? as usize;
                    r.skip(4)?;
                    n += 1;
                    bands += incr;
                    r.skip(8 * bands)?;
                    n += bands;
                }
                if r.read_bool()? {
                    r.skip(8)?;
                    n += 1;
                }
                r.skip(8 * bands)?;
                n += bands;
                Ok(n)
            }
            _ => {
                let _ = start;
                r.skip(8 * cnt - 4)?;
                Ok(cnt)
            }
        }
    }

    fn decode_eld_sbr(&mut self, _r: &mut BitReader) -> Result<()> {
        crate::sbr::dec::decode_eld_sbr(self, _r)
    }

    fn frame_samples(&self) -> usize {
        self.syntax.frame_len
    }

    /// `spectral_to_sample`: tools + synthesis for every element, in the
    /// reference's order (LFE, CCE, CPE, SCE; coupling interleaved).
    fn spectral_to_sample(&mut self) {
        let sx = self.syntax;
        let n = self.frame_samples();
        let sbr_on = self.sbr_state == Some(true);
        for ty in (0..4usize).rev() {
            for id in 0..16usize {
                let Some(el) = self.elements[ty][id].as_ref() else { continue };
                if !el.present {
                    let el = self.elements[ty][id].as_mut().unwrap();
                    for c in el.ch.iter_mut() {
                        c.output.iter_mut().for_each(|v| *v = 0.0);
                    }
                    continue;
                }
                let is_cce = ty == TYPE_CCE as usize;
                if ty <= TYPE_CPE as usize {
                    self.apply_coupling(ty, id, tools::BEFORE_TNS);
                }
                let mut el = self.elements[ty][id].take().unwrap();
                if sx.aot == aot::AAC_LTP && el.ch[0].ics.predictor_present {
                    let nch = if ty == TYPE_CPE as usize { 2 } else { 1 };
                    for c in 0..nch {
                        if el.ch[c].ics.ltp.present {
                            self.apply_ltp(&mut el.ch[c]);
                        }
                    }
                }
                for c in el.ch.iter_mut() {
                    if c.data.tns.present {
                        let (data, ics) = (&mut c.data, &c.ics);
                        tools::apply_tns(&mut data.coeffs, &data.tns, ics, true);
                    }
                }
                self.elements[ty][id] = Some(el);
                if ty <= TYPE_CPE as usize {
                    self.apply_coupling(ty, id, tools::BETWEEN_TNS_AND_IMDCT);
                }
                let mut el = self.elements[ty][id].take().unwrap();
                if !is_cce || el.coup.point == tools::AFTER_IMDCT {
                    let nch = if ty == TYPE_CPE as usize { 2 } else { 1 };
                    for c in 0..nch {
                        self.synthesize(&mut el.ch[c]);
                    }
                    if sbr_on {
                        crate::sbr::dec::apply(self, &mut el, ty as u8, n);
                    }
                }
                self.elements[ty][id] = Some(el);
                if ty <= TYPE_CCE as usize {
                    self.apply_coupling(ty, id, tools::AFTER_IMDCT);
                }
                self.elements[ty][id].as_mut().unwrap().present = false;
            }
        }
    }

    fn apply_coupling(&mut self, ty: usize, id: usize, point: u8) {
        for i in 0..16 {
            let Some(cce) = self.elements[TYPE_CCE as usize][i].as_ref() else { continue };
            if cce.coup.point != point || cce.coup.targets.is_empty() {
                continue;
            }
            let cce = cce.clone();
            let mut index = 0usize;
            for &(t, eid, sel) in &cce.coup.targets {
                if t as usize == ty && eid as usize == id {
                    let target = self.elements[ty][id].as_mut().unwrap();
                    if sel != 1 {
                        Self::couple(&cce, index, point, &mut target.ch[0]);
                        if sel != 0 {
                            index += 1;
                        }
                    }
                    if sel != 2 {
                        Self::couple(&cce, index, point, &mut target.ch[1]);
                        index += 1;
                    }
                } else {
                    index += 1 + (sel == 3) as usize;
                }
            }
        }
    }

    fn couple(cce: &Element, index: usize, point: u8, target: &mut Sce) {
        let Some(gains) = cce.coup.gains.get(index) else { return };
        if point == tools::AFTER_IMDCT {
            let g = gains[0];
            for (d, s) in target.output.iter_mut().zip(cce.ch[0].output.iter()) {
                *d += g * s;
            }
        } else {
            tools::apply_dependent_coupling(&cce.ch[0].ics, &cce.ch[0].data, gains, &mut target.data.coeffs);
        }
    }

    fn apply_ltp(&mut self, sce: &mut Sce) {
        if sce.ics.info.window_sequence == WindowSequence::EightShort {
            return;
        }
        let ltp = sce.ics.ltp;
        let mut pred_time = vec![0f32; 2048];
        let num = if ltp.lag < 1024 { ltp.lag + 1024 } else { 2048 };
        for (i, p) in pred_time.iter_mut().enumerate().take(num) {
            let src = i + 2048 - ltp.lag;
            *p = sce.ltp_state.get(src).copied().unwrap_or(0.0) * ltp.coef;
        }
        let si = synth::SynthIn {
            coeffs: &[],
            seq: sce.ics.info.window_sequence,
            prev_seq: sce.ics.prev_seq,
            kbd: sce.ics.info.window_shape_kbd,
            prev_kbd: sce.ics.prev_kbd,
        };
        let mut pred_freq = synth::ltp_analysis(&self.windows, &si, &mut pred_time);
        if sce.data.tns.present {
            tools::apply_tns(&mut pred_freq, &sce.data.tns, &sce.ics, false);
        }
        for sfb in 0..(sce.ics.info.max_sfb as usize).min(channel::MAX_LTP_LONG_SFB) {
            if ltp.used[sfb] {
                for i in sce.ics.swb[sfb] as usize..sce.ics.swb[sfb + 1] as usize {
                    sce.data.coeffs[i] += pred_freq[i];
                }
            }
        }
    }

    fn synthesize(&mut self, sce: &mut Sce) {
        let sx = self.syntax;
        let n = sx.frame_len;
        match sx.aot {
            aot::ER_AAC_LD => {
                let (ld_sine, lo) = (self.ld_sine.clone(), self.ld_low_overlap.clone());
                synth::imdct_and_window_ld(&ld_sine, &lo, n, &sce.data.coeffs, sce.ics.prev_kbd, &mut self.buf, &mut sce.saved, &mut sce.output);
            }
            aot::ER_AAC_ELD => {
                let window: &[f32] = if n == 480 {
                    &crate::tables_ext::ELD_WINDOW_480
                } else {
                    &crate::tables_ext::ELD_WINDOW_512
                };
                synth::imdct_and_window_eld(window, n, &mut sce.data.coeffs, &mut self.buf, &mut sce.saved, &mut sce.output);
            }
            _ => {
                let si = synth::SynthIn {
                    coeffs: &sce.data.coeffs,
                    seq: sce.ics.info.window_sequence,
                    prev_seq: sce.ics.prev_seq,
                    kbd: sce.ics.info.window_shape_kbd,
                    prev_kbd: sce.ics.prev_kbd,
                };
                synth::imdct_and_window(&self.windows, n, &si, &mut self.buf, &mut sce.saved, &mut sce.output);
                if sx.aot == aot::AAC_LTP {
                    let (seq, kbd) = (sce.ics.info.window_sequence, sce.ics.info.window_shape_kbd);
                    synth::ltp_update(&self.windows, seq, kbd, &self.buf, &sce.saved, &sce.output, &mut sce.ltp_state);
                }
            }
        }
    }

    /// Output samples per channel for this frame (doubled by dual-rate SBR).
    pub(crate) fn output_len(&self) -> usize {
        let n = self.frame_samples();
        if self.sbr_state == Some(true) && self.sbr_ctx.as_ref().map(|c| c.dual_rate()).unwrap_or(false) {
            2 * n
        } else {
            n
        }
    }

    /// The current output sample rate.
    pub fn output_sample_rate(&self) -> u32 {
        if self.output_len() > self.frame_samples() {
            self.cfg.sample_rate * 2
        } else {
            self.cfg.sample_rate
        }
    }

    fn collect_output(&self, pts: Option<i64>) -> DecodedAudio {
        let n = self.output_len();
        let outs = &self.oc.outputs;
        let mut samples = Vec::with_capacity(n * outs.len());
        let chans: Vec<&[f32]> = outs
            .iter()
            .map(|&(ty, iid, sub)| {
                self.elements[ty as usize][iid as usize]
                    .as_ref()
                    .map(|e| &e.ch[sub as usize].output[..n])
                    .unwrap_or(&[])
            })
            .collect();
        for i in 0..n {
            for c in &chans {
                samples.push(c.get(i).copied().unwrap_or(0.0));
            }
        }
        DecodedAudio {
            sample_rate: self.output_sample_rate(),
            channels: outs.len() as u16,
            samples,
            pts,
        }
    }
}

