[package]
name = "rff-format-srt"
description = "Remade FFmpeg (Rust): SubRip (.srt) subtitle container."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["srt", "subrip", "subtitle", "container", "captions"]
categories = ["multimedia", "parser-implementations"]

[dependencies]
rff-core.workspace = true
rff-format.workspace = true
rff-subtitle.workspace = true
