//! Merge `results/av1/speed.tsv` + `stages.tsv` into `REPORT.md`.
//!
//! Reads the TSVs rather than re-measuring, so presentation can change without
//! re-running hours of encodes.

use std::collections::BTreeMap;
use std::path::Path;

struct Speed {
    clip: String,
    class: String,
    width: usize,
    height: usize,
    frames: usize,
    codec: String,
    kind: String,
    source: String,
    wall_ms: f64,
    fps: f64,
    mpx_s: f64,
    kbps: f64,
    psnr: f64,
    ssim: f64,
}

struct Stage {
    codec: String,
    kind: String,
    stage: String,
    scope: String,
    ms: f64,
    calls: u64,
}

fn read_speed(dir: &Path) -> Vec<Speed> {
    let txt = std::fs::read_to_string(dir.join("speed.tsv")).unwrap_or_default();
    txt.lines()
        .skip(1)
        .filter_map(|l| {
            let f: Vec<&str> = l.split('\t').collect();
            if f.len() < 15 {
                return None;
            }
            Some(Speed {
                clip: f[0].into(),
                class: f[1].into(),
                width: f[2].parse().ok()?,
                height: f[3].parse().ok()?,
                frames: f[4].parse().ok()?,
                codec: f[5].into(),
                kind: f[6].into(),
                source: f[7].into(),
                wall_ms: f[8].parse().ok()?,
                fps: f[9].parse().ok()?,
                mpx_s: f[10].parse().ok()?,
                kbps: f[12].parse().ok()?,
                psnr: f[13].parse().unwrap_or(f64::NAN),
                ssim: f[14].parse().unwrap_or(f64::NAN),
            })
        })
        .collect()
}

fn read_stages(dir: &Path) -> Vec<Stage> {
    let txt = std::fs::read_to_string(dir.join("stages.tsv")).unwrap_or_default();
    txt.lines()
        .skip(1)
        .filter_map(|l| {
            let f: Vec<&str> = l.split('\t').collect();
            if f.len() < 9 {
                return None;
            }
            Some(Stage {
                codec: f[1].into(),
                kind: f[2].into(),
                stage: f[3].into(),
                scope: f[4].into(),
                ms: f[5].parse().ok()?,
                calls: f[6].parse().ok()?,
            })
        })
        .collect()
}

fn fmt(v: f64, dp: usize) -> String {
    if v.is_nan() {
        "-".into()
    } else {
        format!("{v:.dp$}")
    }
}

/// Aggregate across clips by SUM of milliseconds — never by averaging per-clip
/// percentages, which would weight a 25 ms QCIF encode the same as a 30 s 1080p
/// one.
fn aggregate(rows: &[&Stage]) -> Vec<(String, String, f64, u64, f64)> {
    let mut by: BTreeMap<String, (String, f64, u64)> = BTreeMap::new();
    for r in rows {
        let e = by.entry(r.stage.clone()).or_insert((r.scope.clone(), 0.0, 0));
        e.1 += r.ms;
        e.2 += r.calls;
    }
    let total = by
        .get("TOTAL")
        .map(|e| e.1)
        .filter(|t| *t > 0.0)
        .unwrap_or_else(|| {
            by.iter()
                .filter(|(k, v)| v.0 == "self" && k.as_str() != "TOTAL")
                .map(|(_, v)| v.1)
                .sum()
        })
        .max(1e-9);
    let mut out: Vec<(String, String, f64, u64, f64)> = by
        .into_iter()
        .map(|(k, (scope, ms, calls))| (k, scope, ms, calls, 100.0 * ms / total))
        .collect();
    out.sort_by(|a, b| b.2.partial_cmp(&a.2).unwrap_or(std::cmp::Ordering::Equal));
    out
}

fn stage_table(out: &mut String, rows: &[&Stage], title: &str, note: &str) {
    if rows.is_empty() {
        return;
    }
    out.push_str(&format!("\n#### {title}\n\n{note}\n\n"));
    out.push_str("| stage | scope | ms | % | calls | ns/call |\n");
    out.push_str("|---|---|---:|---:|---:|---:|\n");
    for (stage, scope, ms, calls, pct) in aggregate(rows) {
        let nspc = if calls > 0 {
            format!("{:.1}", ms * 1e6 / calls as f64)
        } else {
            "-".into()
        };
        out.push_str(&format!(
            "| `{stage}` | {scope} | {} | {} | {calls} | {nspc} |\n",
            fmt(ms, 2),
            fmt(pct, 2)
        ));
    }
}

pub fn generate(dir: &Path) {
    let speed = read_speed(dir);
    let stages = read_stages(dir);
    let mut o = String::new();

    o.push_str("# AV1 — function-level speed report\n\n");
    o.push_str(
        "Our AV1 (`rusty_av1e` / `rusty_av1d`) against the C references and ffmpeg, on the \
         pinned `video-tests` corpus — the SAME pixels the VP9 report uses, so the two are \
         directly comparable. **Everything at default settings on every arm**, \
         single-threaded.\n\n\
         Generated by `video-tests/analyzer-av1` — regenerate with \
         `bash video-tests/run_analysis_av1.sh`.\n\n",
    );
    o.push_str(
        "**How to read the arms.** `ffmpeg` is the bar: `-c:v libaom-av1` at its own defaults \
         for encode and `libdav1d` for decode, timed net of process startup, totals only \
         (the shipped binary is stripped, so it cannot be attributed per function). \
         `libaom` and `dav1d` are our own instrumented builds of the same two libraries \
         ffmpeg links, which *can* be attributed. `ours` is `rusty_av1e`/`rusty_av1d` \
         in process. Note that `dav1d` is the upstream our decoder is a port of, so \
         `ours` vs `dav1d` is a fork-versus-original comparison and the stage names line \
         up almost one-for-one.\n\n",
    );

    if !speed.is_empty() {
        o.push_str("## Throughput\n\n### Encode\n\n");
        o.push_str("| clip | class | size | frames | codec | ms | fps | Mpx/s | kb/s | PSNR dB | SSIM |\n");
        o.push_str("|---|---|---|---:|---|---:|---:|---:|---:|---:|---:|\n");
        for r in speed.iter().filter(|r| r.kind == "encode") {
            o.push_str(&format!(
                "| {} | {} | {}x{} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                r.clip, r.class, r.width, r.height, r.frames, r.codec,
                fmt(r.wall_ms, 1), fmt(r.fps, 2), fmt(r.mpx_s, 3), fmt(r.kbps, 0),
                fmt(r.psnr, 2), fmt(r.ssim, 4)
            ));
        }
        o.push_str("\n### Decode\n\n");
        o.push_str(
            "Each decoder runs against every bitstream produced, because decode cost \
             depends on what the encoder chose, not only on the decoder.\n\n",
        );
        o.push_str("| clip | size | frames | stream | decoder | ms | fps | Mpx/s |\n");
        o.push_str("|---|---|---:|---|---|---:|---:|---:|\n");
        for r in speed.iter().filter(|r| r.kind == "decode") {
            o.push_str(&format!(
                "| {} | {}x{} | {} | {} | {} | {} | {} | {} |\n",
                r.clip, r.width, r.height, r.frames, r.source, r.codec,
                fmt(r.wall_ms, 1), fmt(r.fps, 2), fmt(r.mpx_s, 3)
            ));
        }

        o.push_str("\n### Head to head (Mpx/s, higher is better)\n\n");
        o.push_str("| clip | kind | ours | C reference | ffmpeg | ours vs reference |\n");
        o.push_str("|---|---|---:|---:|---:|---:|\n");
        let mut clips: Vec<String> = speed.iter().map(|r| r.clip.clone()).collect();
        clips.dedup();
        for c in &clips {
            for (kind, refname) in [("encode", "libaom"), ("decode", "dav1d")] {
                let pick = |codec: &str| -> Option<f64> {
                    speed
                        .iter()
                        .find(|r| {
                            &r.clip == c
                                && r.kind == kind
                                && r.codec == codec
                                // For decode, compare on the REFERENCE bitstream:
                                // the stream a decoder in the wild actually sees.
                                && (kind == "encode" || r.source == "libaom")
                        })
                        .map(|r| r.mpx_s)
                };
                let (a, b, f) = (pick("ours"), pick(refname), pick("ffmpeg"));
                if a.is_none() && b.is_none() {
                    continue;
                }
                let ratio = match (a, b) {
                    (Some(a), Some(b)) if b > 0.0 => format!("{:.2}x", a / b),
                    _ => "-".into(),
                };
                o.push_str(&format!(
                    "| {} | {} | {} | {} | {} | {} |\n",
                    c, kind,
                    a.map(|v| fmt(v, 3)).unwrap_or("-".into()),
                    b.map(|v| fmt(v, 3)).unwrap_or("-".into()),
                    f.map(|v| fmt(v, 3)).unwrap_or("-".into()),
                    ratio
                ));
            }
        }
    }

    o.push_str("\n## Per-function breakdown\n\n");
    o.push_str(
        "Aggregated over the corpus by SUM of milliseconds. `scope` distinguishes \
         **self** (exclusive — these sum to 100%), **incl** (contains the nested children \
         listed under it) and **info** (a diagnostic deliberately outside the partition; \
         summing it double-counts).\n\n\
         Both AV1 forks profile nested-inclusively and publish their own nesting, so the \
         report emits the container as `incl` and adds a `(self)` row with the scoped \
         children subtracted — that `(self)` row is the pure-Rust glue that pairs with a \
         C encoder's residue.\n",
    );

    for (kind, refname) in [("encode", "libaom"), ("decode", "dav1d")] {
        for codec in ["ours", refname] {
            let rows: Vec<&Stage> = stages
                .iter()
                .filter(|s| s.kind == kind && s.codec == codec)
                .collect();
            let note = match (codec, kind) {
                ("ours", "encode") =>
                    "`rusty_av1e`. Denominator is the `Total` scope (one whole \
                     `receive_packet`). `partition+mode RDO(self)` is the search / context / \
                     entropy overhead no kernel scope captures.",
                ("ours", "decode") =>
                    "`rusty_av1d`. `tile decode(self)` is the mode-symbol decode and tile \
                     setup left after the recon children are subtracted.",
                (_, "encode") => "libaom, exclusive self-time from the instrumented build.",
                _ => "dav1d, exclusive self-time from the instrumented build — the C original \
                      our decoder is a port of.",
            };
            stage_table(&mut o, &rows, &format!("{codec} — {kind}"), note);
        }
    }

    o.push_str(
        "\n### Caveats that bound these numbers\n\n\
         * Single-threaded on every arm. AV1 encoders in particular scale hard with tiles \
           and frame threads; these numbers are per-core, not peak throughput.\n\
         * `_INSTRUMENT_TAX` (C reference rows) is the profiler measuring itself. When the \
           glue bucket is the same order as the tax, there is no hidden work left.\n\
         * The AV1 forks' profilers are COMPILE-TIME gated, so the speed pass and the \
           stages pass come from two different binaries — the speed binary carries no \
           instrumentation at all.\n\
         * `ours` is measured against the local `rusty-av1-toolkit` checkout, which must sit \
           at the rev pinned in the root `Cargo.toml` or this measures a different encoder \
           than the one `rff` ships.\n",
    );

    let path = dir.join("REPORT.md");
    std::fs::write(&path, o).expect("write REPORT.md");
    eprintln!("wrote {}", path.display());
}
