[package]
name = "rff-codec-png"
description = "Remade FFmpeg (Rust): PNG still-image codec (RGB/RGBA)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["png", "image", "codec", "decoder", "encoder"]
categories = ["multimedia", "multimedia::images"]

[dependencies]
rff-core.workspace = true
rff-codec.workspace = true
rusty_png.workspace = true
