[package]
name = "rff-codec-opus"
description = "Remade FFmpeg (Rust): Opus audio codec."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["opus", "audio", "codec", "decoder", "encoder"]
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]

[dependencies]
rff-core.workspace = true
rff-codec.workspace = true
rusty_opus.workspace = true
