[package]
name = "rff-format-mp3"
description = "Remade FFmpeg (Rust): native MP3 elementary-stream container."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["mp3", "container", "audio", "demuxer", "muxer"]
categories = ["multimedia", "multimedia::audio", "parser-implementations"]

[dependencies]
rff-core.workspace = true
rff-format.workspace = true
