[package]
name = "rff-codec-jxl"
description = "Remade FFmpeg (Rust): JPEG XL image decoder."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["jpegxl", "jxl", "image", "codec", "decoder"]
categories = ["multimedia", "multimedia::images"]

[dependencies]
rff-core.workspace = true
rff-codec.workspace = true
jxl-oxide.workspace = true
