[package]
name = "rff-format-mp4"
description = "Remade FFmpeg (Rust): MP4 / MOV (ISOBMFF) demuxer."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["mp4", "mov", "isobmff", "container", "demuxer"]
categories = ["multimedia", "parser-implementations"]

[dependencies]
rff-core.workspace = true
rff-format.workspace = true
