[package]
name = "rff-format-jxl"
description = "Remade FFmpeg (Rust): JPEG XL single-image container."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://github.com/Remade-With-Rust/remade_ffmpeg_rs"
readme = "README.md"
keywords = ["jpegxl", "jxl", "container", "image", "demuxer"]
categories = ["multimedia", "multimedia::images", "parser-implementations"]

[dependencies]
rff-core.workspace = true
rff-format.workspace = true
jxl-oxide.workspace = true
